name: server
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies: 
  args: ^2.3.1
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.4.2
  dotenv: ^4.0.1
  http: ^0.13.4
  intl: ^0.17.0
  mailer: ^5.2.0
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  supabase: ^0.3.6
  uuid: ^3.0.6
